### ISSUE TITLE
Embed in Godot?

### ISSUE THREAD

**Issue by michaelgundlach** [NoctemCat/BottomPanelShortcuts#1]
This is great and finally adds a shortcut to toggle the bottom panel, which is all I wanted (I didn't need to toggle specific windows in the bottom panel.)

Why not put the Toggle Bottom Panel shortcut directly into the editor, like how Ctrl-\ or Cmd-\ toggles the scripts panel?  I would suggest using Ctrl-/ or Cmd-/ for toggling the bottom panel, since on Mac Cmd-Space is Spotlight Search (and for symmetry with the Scripts Panel shortcut.)

**Comment by michaelgundlach** [comment]
I mean, rather than doing it as a plugin that someone has to discover and install, they'd find the shortcut when they search for "bottom" in Editor Settings -> Shortcuts.

**Comment by NoctemCat** [comment]
Skill issue on my side. I can write a simple plugin, I can't add changes to Godot itself. 

I will be glad if somebody could do this, but for now it will be just a plugin.

And my solution itself is kinda hacky. It will work and I'm content with it being a plugin, but I'm not sure I want this as a part of Godot.

**Comment by michaelgundlach** [comment]
LOL, I tried understanding your code and couldn't figure out where the
actual toggling was happening, whereas looking through the C++ code I
figured I could at least copy-and-modify the approach used for the Scripts
panel.

I don't have the skill for either, and I'm just grateful I can press Cmd-/
now and toggle the panel.  Thanks!

**Comment by NoctemCat** [comment]
Haha, I can understand you, it really is hacky. It listens for 'toggle' signal on the bottom buttons in the editor, and when that signal happens it updates button variable. After when your input matches a shortcut it uses saved button variable, and emits a 'toggle' signal on that button.

Thanks to that it works with all bottom panels, even the ones that would be added by other plugins.

**Comment by NoctemCat** [comment]
All the other things are checks that will make sure it is working correctly and without error

**Comment by michaelgundlach** [comment]
Oh, clever!

**Comment by NoctemCat** [comment]
![image](https://github.com/NoctemCat/BottomPanelShortcuts/assets/22471296/17215503-8cd4-4d2b-a304-af460370bc4f)

Found out it is now possible in the engine with 'Toggle Last Opened Bottom Panel' so I'm closing this issue as completed (not by me, but completed nonetheless), version v4.3.beta2.official [b75f0485b]
